version: 2
jobs:
  build:

    working_directory: ~/repo

    docker:
    - image: circleci/openjdk:8-jdk

    steps:

    - checkout
    - run:
        name: Clean & install
        command: |
          mkdir -p test-results¯
          ./gradlew clean build -x test --no-daemon
    - run:
        name: Tests
        command: ./gradlew test
    - store_test_results:
        path: build/test-results/test
