version: 2
jobs:
  build:

    working_directory: ~/repo

    docker:
    - image: circleci/openjdk:8-jdk

    steps:

    - checkout
    - run:
        name: Clean & install
        command: |
          mkdir -p test-results
          ./gradlew clean build -x test --no-daemon
    - run:
        name: Tests
        command: ./gradlew test
    - store_test_results:
        path: build/test-results

    - run:
        name: Collect artifacts
        command: |
          mkdir -p artifacts/libs
          cp -pR build/libs/* artifacts/libs || true
          cp -pR build/resources/main/scenarioo-schemas/*.xsd artifacts/schema || true
          cp -pR LICENSE.txt artifacts/

    - store_artifacts:
        path: artifacts
        destination: /
